title: "FloripaJS"
description: "A maior comunidade front-end de Florianópolis"

social:
  github: "https://github.com/floripajs"
  twitter: "https://twitter.com/floripajs"
  facebook: "http://fb.com/floripajs"
  facebook_group: "http://fb.com/groups/floripajs"
  slack: "http://slack.floripajs.org"
  youtube: "https://www.youtube.com/floripajs"
